<?php
/**
 * Created by PhpStorm.
 * User: quangthinh
 * Date: 7/20/2016
 * Time: 4:30 PM
 */

namespace quangthinh\yii\setting;


use Yii;

class Model extends \yii\base\Model
{
    public function setting()
    {
        return Yii::$app->get('setting');
    }

    public function section()
    {
        return '';
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // init setting data
        $fields = $this->saveFields();
        $setting = $this->setting();
        $section = $this->section();
        foreach ($fields as $field) {
            $this->$field = $setting[$section . $field];
        }
    }

    public function saveFields()
    {
        return $this->attributes();
    }

    /**
     * validate rules
     */
    public function rules()
    {
        return [$this->saveFields(), 'string'];
    }

    /**
     * Update setting data in model
     */
    public function update()
    {
        $saveFields = $this->saveFields();
        $setting = $this->setting();
        
        $section = $this->section();
        foreach ($saveFields as $field) {
            $setting[$section . $field] = $this->$field;
        }
    }
}