<?php
/**
 * Created by PhpStorm.
 * User: quangthinh
 * Date: 7/20/2016
 * Time: 4:30 PM
 */

namespace quangthinh\yii\setting;


use Yii;
use yii\db\ActiveRecord;
use yii\helpers\StringHelper;

class Model extends \yii\base\Model
{
    public static function setting()
    {
        return Yii::$app->get('setting');
    }

    public static function section()
    {
        return StringHelper::basename(get_called_class());
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // init setting data
        /**
         * @var $className Model
         */
        $className = get_class($this);

        $fields = $this->saveFields();
        $setting = $className::setting();
        $section = $className::section();
        foreach ($fields as $field) {
            $this->$field = $setting[$section . $field];
        }
    }

    public function saveFields()
    {
        return $this->attributes();
    }

    /**
     * validate rules
     */
    public function rules()
    {
        /**
         * @var $className Model
         */
        $className = get_class($this);
        return [$className::saveFields(), 'string'];
    }

    /**
     * Update setting data in model
     */
    public function update()
    {
        /**
         * @var $className Model
         */
        $className = get_class($this);

        $saveFields = $this->saveFields();
        $setting = $className::setting();
        
        $section = $className::section();
        foreach ($saveFields as $field) {
            $setting[$section . $field] = $this->$field;
        }
    }
}