<?php

use yii\db\Migration;

class m160718_042239_create_setting extends Migration
{
    public function createTable($table, $columns, $options = null)
    {
        if ($options === null) {
            if ($this->db->driverName === 'mysql') {
                // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
                $options = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
            }
        }

        parent::createTable($table, $columns, $options); // TODO: Change the autogenerated stub
    }
    
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
        $this->createTable('{{%setting}}', [
            'key' => $this->string()->notNull(),
            'data' => $this->text(),
        ]);

        $this->addPrimaryKey('pk_setting', '{{%setting}}', ['key']);
    }

    public function safeDown()
    {
        $this->dropTable('{{%setting}}');
    }
}
